pub mod chainspec;
pub mod consensus;
pub mod evm;
mod hardforks;
pub mod metrics;
pub mod node;
pub mod rpc;
pub mod shared;
pub use node::primitives::BscPrimitives;
pub use node::primitives::{BscBlock, BscBlockBody, BscBlobTransactionSidecar};
mod system_contracts;
pub use system_contracts::SLASH_CONTRACT;
pub use system_contracts::{encode_add_node_ids_call, encode_remove_node_ids_call};
